In [31]:
import numpy as np
from datetime import datetime as dt
v = [1, 2, 3, 4, 5, 6]

# lets create a numpy array
w = np.array([1, 2, 3, 4, 5, 6])

In [45]:
start = dt.now()
newv = [num + 1 for num in v]
stop = dt.now()

total_time = stop - start

print(f"total time = {total_time}")

total time = 0:00:00.000084


In [46]:
start = dt.now()
newv = [num + 1 for num in v]
stop = dt.now()
total_time = stop - start
print(f"total time = {total_time}")

total time = 0:00:00.000056


In [47]:

# creating a 1d array
nums = [1, 2, 3, 4, 5]
nums_arr = np.array(nums)
print(nums_arr)

[1 2 3 4 5]


In [48]:
# lets create a 2d array
row1 = [2, 4, 5]
row2 = [0, 5, 7]
nested_list = [row1, row2]
matrix = np.array(nested_list)
print(matrix)

[[2 4 5]
 [0 5 7]]


In [55]:
# lets create an array of zero
zeros = np.zeros((3, 7))
ones = np.ones((3, 7))

#lets create an array with linearly spaced values
arr_lsv = np.linspace(0, 100, 25) # (0, 100, 25) means 25 evenly spaced nums from 0 - 100
print(arr_lsv)
print(zeros)
print(ones)


[  0.           4.16666667   8.33333333  12.5         16.66666667
  20.83333333  25.          29.16666667  33.33333333  37.5
  41.66666667  45.83333333  50.          54.16666667  58.33333333
  62.5         66.66666667  70.83333333  75.          79.16666667
  83.33333333  87.5         91.66666667  95.83333333 100.        ]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
